---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-autoscaler
  labels:
    app.kubernetes.io/name: argocd-autoscaler
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-autoscaler
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: argocd-autoscaler
      labels:
        app.kubernetes.io/name: argocd-autoscaler
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command:
        - /manager
        args:
          - --namespaces=$(NAMESPACE)
          - --leader-elect
          - --health-probe-bind-address=:8081
        image: ghcr.io/plumber-cd/argocd-autoscaler:latest
        imagePullPolicy: IfNotPresent
        name: argocd-autoscaler
        ports: []
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {}
        volumeMounts: []
      volumes: []
      serviceAccountName: argocd-autoscaler
      terminationGracePeriodSeconds: 10
