apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: argocd-autoscaler
  name: argocd-autoscaler-leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-autoscaler-leader-election
subjects:
- kind: ServiceAccount
  name: argocd-autoscaler
