---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaler.argoproj.io
  resources:
  - longestprocessingtimepartitions
  - mostwantedtwophasehysteresisevaluations
  - prometheuspolls
  - replicasetscalers
  - robustscalingnormalizers
  - secrettypeclustershardmanagers
  - weightedpnormloadindexes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaler.argoproj.io
  resources:
  - longestprocessingtimepartitions/finalizers
  - mostwantedtwophasehysteresisevaluations/finalizers
  - prometheuspolls/finalizers
  - replicasetscalers/finalizers
  - robustscalingnormalizers/finalizers
  - secrettypeclustershardmanagers/finalizers
  - weightedpnormloadindexes/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaler.argoproj.io
  resources:
  - longestprocessingtimepartitions/status
  - mostwantedtwophasehysteresisevaluations/status
  - prometheuspolls/status
  - replicasetscalers/status
  - robustscalingnormalizers/status
  - secrettypeclustershardmanagers/status
  - weightedpnormloadindexes/status
  verbs:
  - get
  - patch
  - update
