---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - autoscaler.argoproj.iom
  resources:
  - polls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaler.argoproj.iom
  resources:
  - polls/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaler.argoproj.iom
  resources:
  - polls/status
  verbs:
  - get
  - patch
  - update
