---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaler.argoproj.io
  resources:
  - longestprocessingtimepartitions
  - mostwantedtwophasehysteresisevaluations
  - prometheuspolls
  - robustscalingnormalizers
  - secrettypeclusterdiscoveries
  - weightedpnormloadindexes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaler.argoproj.io
  resources:
  - longestprocessingtimepartitions/finalizers
  - mostwantedtwophasehysteresisevaluations/finalizers
  - prometheuspolls/finalizers
  - robustscalingnormalizers/finalizers
  - secrettypeclusterdiscoveries/finalizers
  - weightedpnormloadindexes/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaler.argoproj.io
  resources:
  - longestprocessingtimepartitions/status
  - mostwantedtwophasehysteresisevaluations/status
  - prometheuspolls/status
  - robustscalingnormalizers/status
  - secrettypeclusterdiscoveries/status
  - weightedpnormloadindexes/status
  verbs:
  - get
  - patch
  - update
