{
 "title": "ArgoCD Autoscaler",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total{namespace=~\"$namespace\"}, job)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total,namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total{namespace=~\"$namespace\", job=~\"$job\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Polling",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Discovered Shards",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(argocd_autoscaler_shard_manager_discovered_shards) by (shard_manager_type,shard_manager_ref)",
       "legendFormat": "{{shard_manager_ref}} ({{shard_manager_type}})"
      }
     ]
    },
    {
     "title": "Load Index",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(argocd_autoscaler_load_index_values) by (load_index_type,load_index_ref,shard_name)",
       "legendFormat": "{{load_index_ref}} ({{load_index_type}}): {{shard_name}}"
      }
     ]
    },
    {
     "title": "Polled Values",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(argocd_autoscaler_poll_values) by (poll_type,poll_ref,shard_name,metric_id)",
       "legendFormat": "{{poll_ref}} ({{poll_type}}): {{shard_name}}/{{metric_id}}"
      }
     ]
    },
    {
     "title": "Normalized Values",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(argocd_autoscaler_normalizer_values) by (normalizer_type,normalizer_ref,shard_name,metric_id)",
       "legendFormat": "{{normalizer_ref}} ({{normalizer_type}}): {{shard_name}}/{{metric_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Partitioning",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Partitioning (partitioner)",
     "type": "state-timeline",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace((sum(argocd_autoscaler_partition_shards) by (partition_type,partition_ref,replica_id)),\n    \"replica_id\", \"0$1\", \"replica_id\", \"^([0-9])$\"\n)",
       "legendFormat": "{{partition_ref}} ({{partition_type}}): {{replica_id}}"
      }
     ]
    },
    {
     "title": "Partitioning (projected)",
     "type": "state-timeline",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace((sum(argocd_autoscaler_evaluation_projected_shards) by (evaluation_type,evaluation_ref,replica_id)),\n    \"replica_id\", \"0$1\", \"replica_id\", \"^([0-9])$\"\n)",
       "legendFormat": "{{evaluation_ref}} ({{evaluation_type}}): {{replica_id}}"
      }
     ]
    },
    {
     "title": "Partitioning (applied)",
     "type": "state-timeline",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "label_replace((sum(argocd_autoscaler_evaluation_shards) by (evaluation_type,evaluation_ref,replica_id)),\n    \"replica_id\", \"0$1\", \"replica_id\", \"^([0-9])$\"\n)",
       "legendFormat": "{{evaluation_ref}} ({{evaluation_type}}): {{replica_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Load Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Load per Replica (partitioner)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(argocd_autoscaler_partition_replicas_total_load) by (partition_type,partition_ref,replica_id)",
       "legendFormat": "{{partition_ref}} ({{partition_type}}): {{replica_id}}"
      }
     ]
    },
    {
     "title": "Total Load per Replica (projected)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(argocd_autoscaler_evaluation_projected_replicas_total_load) by (evaluation_type,evaluation_ref,replica_id)",
       "legendFormat": "{{evaluation_ref}} ({{evaluation_type}}): {{replica_id}}"
      }
     ]
    },
    {
     "title": "Total Load per Replica (applied)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 17, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(argocd_autoscaler_evaluation_replicas_total_load) by (evaluation_type,evaluation_ref,replica_id)",
       "legendFormat": "{{evaluation_ref}} ({{evaluation_type}}): {{replica_id}}"
      }
     ]
    },
    {
     "title": "Changes",
     "type": "gauge",
     "gridPos": { "h": 12, "w": 7, "x": 17, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(argocd_autoscaler_scaler_replica_set_changes_total) by (scaler_type,scaler_ref,replica_set_controller_kind,replica_set_controller_ref)",
       "legendFormat": "{{scaler_ref}} ({{scaler_type}}): {{replica_set_controller_ref}} ({{replica_set_controller_type}})"
      }
     ]
    }
   ]
  }
 ]
}