{
 "title": "Custom-Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total{namespace=~\"$namespace\"}, job)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total{namespace=~\"$namespace\", job=~\"$job\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "argocd_autoscaler_shard_manager_discovered_shards (gauge)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "number" } },
   "targets": [
    {
     "expr": "sum(argocd_autoscaler_shard_manager_discovered_shards) by (shard_manager_type,shard_manager_ref)"
    }
   ]
  },
  {
   "title": "argocd_autoscaler_poll_values (gauge)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "number" } },
   "targets": [
    {
     "expr": "sum(argocd_autoscaler_poll_values) by (poll_type,poll_ref,shard_name,metric_id)"
    }
   ]
  },
  {
   "title": "argocd_autoscaler_normalizer_values (gauge)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "number" } },
   "targets": [
    {
     "expr": "sum(argocd_autoscaler_normalizer_values) by (normalizer_type,normalizer_ref,shard_name,metric_id)"
    }
   ]
  },
  {
   "title": "argocd_autoscaler_load_index_values (gauge)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "number" } },
   "targets": [
    {
     "expr": "sum(argocd_autoscaler_load_index_values) by (load_index_type,load_index_ref,shard_name)"
    }
   ]
  },
  {
   "title": "argocd_autoscaler_partition_shards (gauge)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "number" } },
   "targets": [
    {
     "expr": "sum(argocd_autoscaler_partition_shards) by (partition_type,partition_ref,replica_id)"
    }
   ]
  },
  {
   "title": "argocd_autoscaler_partition_replicas_total_load (gauge)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "number" } },
   "targets": [
    {
     "expr": "sum(argocd_autoscaler_partition_replicas_total_load) by (partition_type,partition_ref,replica_id)"
    }
   ]
  },
  {
   "title": "argocd_autoscaler_evaluation_projected_shards (gauge)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "number" } },
   "targets": [
    {
     "expr": "sum(argocd_autoscaler_evaluation_projected_shards) by (evaluation_type,evaluation_ref,replica_id)"
    }
   ]
  },
  {
   "title": "argocd_autoscaler_evaluation_projected_replicas_total_load (gauge)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "number" } },
   "targets": [
    {
     "expr": "sum(argocd_autoscaler_evaluation_projected_replicas_total_load) by (evaluation_type,evaluation_ref,replica_id)"
    }
   ]
  },
  {
   "title": "argocd_autoscaler_evaluation_shards (gauge)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "number" } },
   "targets": [
    {
     "expr": "sum(argocd_autoscaler_evaluation_shards) by (evaluation_type,evaluation_ref,replica_id)"
    }
   ]
  },
  {
   "title": "argocd_autoscaler_evaluation_replicas_total_load (gauge)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "number" } },
   "targets": [
    {
     "expr": "sum(argocd_autoscaler_evaluation_replicas_total_load) by (evaluation_type,evaluation_ref,replica_id)"
    }
   ]
  },
  {
   "title": "argocd_autoscaler_scaler_replica_set_changes_total (counter)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "number" } },
   "targets": [
    {
     "expr": "sum(argocd_autoscaler_scaler_replica_set_changes_total) by (scaler_type,scaler_ref,replica_set_controller_kind,replica_set_controller_ref)"
    }
   ]
  }
 ]
}