apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-application-controller
spec:
  replicas: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-application-controller
      argocd.paramount.tech/name: argocd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-application-controller
        argocd.paramount.tech/name: argocd
    spec:
      containers:
      - name: argocd-application-controller
        image: registry.k8s.io/pause:3.1
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
