apiVersion: autoscaler.argoproj.io/v1alpha1
kind: MostWantedTwoPhaseHysteresisEvaluation
metadata:
  labels:
    app.kubernetes.io/name: argocd-autoscaler
  name: mostwantedtwophasehysteresisevaluation-sample
spec:
  partitionProviderRef:
    apiGroup: autoscaler.argoproj.io
    kind: LongestProcessingTimePartition
    name: argocd-autoscaler-longestprocessingtimepartition-sample
  pollingPeriod: 5s
  stabilizationPeriod: 1m
  minimumSampleSize: 3
