apiVersion: autoscaler.argoproj.io/v1alpha1
kind: PrometheusPoll
metadata:
  labels:
    app.kubernetes.io/name: argocd-autoscaler
  name: prometheuspoll-sample
spec:
  shardManagerRef:
    apiGroup: autoscaler.argoproj.io
    kind: SecretTypeClusterShardManager
    name: argocd-autoscaler-secrettypeclustershardmanager-sample
  period: 5s
  address: http://prometheus-operated.prometheus.svc.cluster.local:9090
  metrics:
  - id: up
    query: up
