apiVersion: autoscaler.argoproj.io/v1alpha1
kind: ReplicaSetScaler
metadata:
  labels:
    app.kubernetes.io/name: argocd-autoscaler
  name: sample
spec:
  partitionProviderRef:
    apiGroup: autoscaler.argoproj.io
    kind: MostWantedTwoPhaseHysteresisEvaluation
    name: sample
  shardManagerRef:
    apiGroup: autoscaler.argoproj.io
    kind: SecretTypeClusterShardManager
    name: sample
  replicaSetControllerRef:
    apiGroup: apps
    kind: StatefulSet
    name: argocd-application-controller
  mode: {}
    # default:
    #   rolloutRestart: true
    # x0y: {}
