apiVersion: autoscaler.argoproj.io/v1alpha1
kind: SecretTypeClusterShardManager
metadata:
  labels:
    app.kubernetes.io/name: argocd-autoscaler
  name: sample
spec:
  labelSelector:
    matchLabels:
      test.argocd.argoproj.io/secret-type: cluster
