apiVersion: autoscaler.argoproj.io/v1alpha1
kind: WeightedPNormLoadIndex
metadata:
  labels:
    app.kubernetes.io/name: argocd-autoscaler
  name: sample
spec:
  metricValuesProviderRef:
    apiGroup: autoscaler.argoproj.io
    kind: RobustScalingNormalizer
    name: sample
  p: 2
  weights:
  - id: up
    weight: "1"
