apiVersion: autoscaler.argoproj.io/v1alpha1
kind: WeightedPNormLoadIndex
metadata:
  labels:
    app.kubernetes.io/name: argocd-autoscaler
  name: default
spec:
  metricValuesProviderRef:
    apiGroup: autoscaler.argoproj.io
    kind: RobustScalingNormalizer
    name: default
  p: 1
  weights:
  - id: argocd_app_info
    weight: "0.05"
  - id: argocd_cluster_api_resource_objects
    weight: "0.1"
  - id: argocd_cluster_api_resources
    weight: "0.1"
  - id: argocd_app_reconcile_count
    weight: "0.15"
  - id: argocd_cluster_events_total
    weight: "0.2"
  - id: argocd_app_k8s_request_total
    weight: "0.2"
  - id: rest_client_requests_total
    weight: "0.2"
