apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-application-controller
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-application-controller
      argocd.paramount.tech/name: argocd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-application-controller
        argocd.paramount.tech/name: argocd
    spec:
      containers:
      - name: argocd-application-controller
        image: registry.k8s.io/pause:3.1
        env:
        - name: ARGOCD_CONTROLLER_REPLICAS
          value: "2"
