apiVersion: v1
kind: Namespace
metadata:
  name: argocd-autoscaler-test
---
apiVersion: v1
kind: Secret
metadata:
  name: prometheuspoll-sample
  namespace: argocd-autoscaler-test
  labels:
    argocd.argoproj.io/secret-type: cluster
stringData:
  name: sample-cluster
  server: https://kubernetes.default.svc
type: Opaque
---
apiVersion: autoscaler.argoproj.io/v1alpha1
kind: PrometheusPoll
metadata:
  name: prometheuspoll-sample
  namespace: argocd-autoscaler-test
spec:
  initialDelay: 5s
  period: 30s
  address: http://localhost:9090
  metrics:
  - id: argocd_app_info
    query: |-
      quantile_over_time(
        0.95,
        (
          sum by() (argocd_app_info{job="argocd-metrics",namespace="argocd",dest_server="{{ .server }}"})
        )[24h:1m]
      )
