apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: cluster
  name: sample-cluster
stringData:
  name: sample-cluster
  server: https://kubernetes.default.svc
type: Opaque
