namespace: argocd-autoscaler

resources:
- ../../default-secured
- service_account.yaml
- role_metrics_auth.yaml
- role_metrics_auth_binding.yaml

patches:
- path: manager_zap_devel.yaml
  target:
    kind: Deployment
