# This patch adds the args to allow exposing the metrics endpoint
- op: add
  path: /spec/template/spec/containers/0/args/0
  value: --zap-devel
# - op: add
#   path: /spec/template/spec/containers/0/args/0
#   value: --zap-encoder=console
# - op: add
#   path: /spec/template/spec/containers/0/args/0
#   value: --zap-log-level=1
