# The following manifests contain a self-signed issuer CR and a metrics certificate CR.
# More document can be found at https://docs.cert-manager.io
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder
  name: argocd-autoscaler-metrics-certs  # this name should match the one appeared in kustomizeconfig.yaml
spec:
  dnsNames:
  - metrics
  issuerRef:
    kind: Issuer
    name: argocd-autoscaler-selfsigned-issuer
  secretName: argocd-autoscaler-metrics-server-cert
