# The following manifests contain a self-signed issuer CR and a metrics certificate CR.
# More document can be found at https://docs.cert-manager.io
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: argocd-autoscaler
  name: argocd-autoscaler-metrics
spec:
  dnsNames:
  - metrics
  issuerRef:
    kind: Issuer
    name: argocd-autoscaler-selfsigned
  secretName: argocd-autoscaler-metrics-certs
