- op: replace
  path: /spec/endpoints/0/scheme
  value: https
- op: add
  path: /spec/endpoints/0/bearerTokenFile
  value: /var/run/secrets/kubernetes.io/serviceaccount/token
- op: add
  path: /spec/endpoints/0/tlsConfig
  value:
    serverName: metrics
    insecureSkipVerify: false
    ca:
      secret:
        name: argocd-autoscaler-metrics-server-cert
        key: ca.crt
    cert:
      secret:
        name: argocd-autoscaler-metrics-server-cert
        key: tls.crt
    keySecret:
      name: argocd-autoscaler-metrics-server-cert
      key: tls.key
