apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: argocd-autoscaler
    metrics: enabled
  name: argocd-autoscaler-metrics
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-autoscaler
