- op: add
  path: /spec/template/spec/containers/0/args/0
  value: --metrics-bind-address=:8080
- op: add
  path: /spec/template/spec/containers/0/args/0
  value: --metrics-secure=false
- op: add
  path: /spec/template/spec/containers/0/ports/-
  value:
    name: metrics
    containerPort: 8080
    protocol: TCP
